services:
  database:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
    driver: local